# Variables
@baseUrl = http://localhost:3333

# Health check
# @name healthCheck
GET {{baseUrl}}/health

###

# Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
    "name": "Sala de testes x",
    "description": "Esta é uma nova Sala de testes"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get room and own questions
# @name getRoomAndQuestions
GET {{baseUrl}}/rooms/{{roomId}}

###

# Get room questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create question
# @name createQuestion
POST {{baseUrl}}/rooms/{{roomId}}/questions
Content-Type: application/json

{
    "question": "Esta é uma nova questão de testes de testes"
}