# Variables
@baseUrl = http://localhost:3333
@authToken = nlw-agents-secret-token-2025

# Health check
# @name healthCheck
GET {{baseUrl}}/health

###

# Get rooms
# @name getRooms
GET {{baseUrl}}/rooms
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

# Create room (protegido)
# @name createRoom
POST {{baseUrl}}/rooms
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "name": "Sala de testes Gui",
    "description": "Esta é uma nova Sala de testes"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get room and own questions (protegido)
# @name getRoomAndQuestions
GET {{baseUrl}}/rooms/{{roomId}}
Authorization: Bearer {{authToken}}

###

# Get room questions (protegido)
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions
Authorization: Bearer {{authToken}}

###

# Get room summary (protegido)
# @name getRoomTranscription
GET {{baseUrl}}/rooms/{{roomId2}}/transcription
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

# Get room summary (protegido)
# @name getRoomSummary
GET {{baseUrl}}/rooms/{{roomId}}/summary
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

# Create question (protegido)
# @name createQuestion
POST {{baseUrl}}/rooms/{{roomId}}/questions
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "question": "Esta é uma nova questão de testes de testes"
}

###

# Create question (protegido)
# @name createQuestion2
POST {{baseUrl}}/rooms/6b70810c-74ff-4ce9-2665-dbe392f0610b/questions
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "question": "Quem é o Batman?"
}

###

# Create Product Link
# @name createProductLink
POST {{baseUrl}}/product
Content-Type: application/json

{
    "message": "💖 Jogo de Talheres 18 36 54 e 72 Peças Garfo Faca e Colher Prime Cozinha Aço Inox Premium ❌ De R$ 82,97 ✅ Por R$ 24,89 ⭐⭐⭐⭐⭐ (Bem Avaliado) Compre no link👇🏼🛍️ ➡️ https://s.shopee.com.br/9ADnTovy46"
}

###

# ❌ Teste sem token (deve dar erro 401)
# @name testWithoutToken
GET {{baseUrl}}/rooms/6b70810c-74ff-4ce9-2665-dbe392f0610b